### ISSUE TITLE
Unable to follow remote accounts

### ISSUE THREAD

**Issue by nolanlawson** [tootcafe/discussions#32]
Something went wrong with the 2.3.3 upgrade, and now users aren't able to follow remote accounts... not sure what's going on here, but this is the Sidekiq error:

```
{"context":"Job raised exception","job":{"class":"ActivityPub::SynchronizeFeaturedCollectionWorker","args":
[15043],"retry":true,"queue":"pull","jid":"335903d76b209066e49227a0","created_at":1522532029.2076547,"enqueued_at":1522664534.342483,"error_message":"undefined method 
`featured_collection_url' for nil:NilClass","error_class":"NoMethodError","failed_at":1522547724.9548652,"retry_count":5,"retried_at
":1522663788.5058508},"jobstr":"{\"class\":\"ActivityPub::SynchronizeFeaturedCollectionWorker\",\"args\":[15043],\"retry\":true,\"queue\":\"pull\",\"jid\":\"335903d76b209066e49227a0\",\"created_at
\":1522532029.2076547,\"enqueued_at\":1522664534.342483,\"error_message\":\"undefined method `featured_collection_url' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at
\":1522547724.9548652,\"retry_count\":5,\"retried_at\":1522663788.5058508}"}
```

The important bit seems to be:

```
undefined method `featured_collection_url' for nil:NilClass
```

I took a look at the diff between http://github.com/tootcafe/mastodon and the `v2.3.3` branch of tootsuite master and I'm not seeing anything that would cause this error. Feeling a bit stumped here. :confused:

More details: https://github.com/tootsuite/mastodon/issues/6796#issuecomment-378012735

**Comment by nolanlawson** [comment]
More output:

```
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: 2018-04-02T19:22:51.565Z 93829 TID-owt8f6q28 WARN: NoMethodError: undefined method `featured_collection_url' for nil:NilClass
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: 2018-04-02T19:22:51.567Z 93829 TID-owt8f6q28 WARN: /home/mastodon/live/app/services/activitypub/process_account_service.rb:30:in `call'
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: /home/mastodon/live/app/services/activitypub/fetch_remote_account_service.rb:23:in `call'
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: /home/mastodon/live/app/services/activitypub/fetch_remote_status_service.rb:19:in `call'
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: /home/mastodon/live/app/services/activitypub/fetch_featured_collection_service.rb:26:in `block in process_items'
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: /home/mastodon/live/app/services/activitypub/fetch_featured_collection_service.rb:26:in `map'
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: /home/mastodon/live/app/services/activitypub/fetch_featured_collection_service.rb:26:in `process_items'
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: /home/mastodon/live/app/services/activitypub/fetch_featured_collection_service.rb:17:in `call'
Apr 02 19:22:51 tootcafe-charlie bundle[93829]: /home/mastodon/live/app/workers/activitypub/synchronize_featured_collection_worker.rb:9:in `perform'
```

**Comment by nolanlawson** [comment]
Seems the error is thrown at [this line of code](https://github.com/tootsuite/mastodon/blob/123a343d116d3e83cbd04460cc7bd0b6f3d208c4/app/services/activitypub/process_account_service.rb#L31)? Is it possible that if Redis isn't able to get the lock, then the `@account` would be null?

**Comment by nolanlawson** [comment]
Restarted Redis and Postgres and all Mastodon services, no dice. 😞

**Comment by nolanlawson** [comment]
Looks like the relevant call stack is:

- [fetch_remote_status_service:19](https://github.com/tootsuite/mastodon/blob/123a343d116d3e83cbd04460cc7bd0b6f3d208c4/app/services/activitypub/fetch_remote_status_service.rb#L19)
- [fetch_remote_account_service:23](https://github.com/tootsuite/mastodon/blob/123a343d116d3e83cbd04460cc7bd0b6f3d208c4/app/services/activitypub/fetch_remote_account_service.rb#L23)
- [process_account_service:31](https://github.com/tootsuite/mastodon/blob/123a343d116d3e83cbd04460cc7bd0b6f3d208c4/app/services/activitypub/process_account_service.rb#L31)

Given that `fetch_remote_status_service` does check for the possibility of nil accounts, and `fetch_remote_account_service` just passes the result from `process_account_service` straight back, it seems there needs to be an extra nil check in `process_account_service`.

**Comment by nolanlawson** [comment]
The hotpatch (https://github.com/tootcafe/mastodon/commit/ffaca18a4c7afe3f64bd0b4ec598dbed5478cf4f) seems to have fixed it. Sidekiq slowly working its way through a large backlog.

**Comment by nolanlawson** [comment]
To be clear: this bug also appears to have broken federation. We were cut off from the rest of the fediverse for a few days. 😬

**Comment by nolanlawson** [comment]
Federation started working again slowly after applying the patch, but we are still at around 100k Sidekiq jobs, slowly getting through them. Most are just ActivityPub::SynchronizeFeaturedCollectionWorker with the same argument (an account ID), which is the job that was previously failing. Somehow it managed to clog up most of the Sidekiq `pull` queue apparently.
